### ISSUE TITLE
Search does not work after changing language

### ISSUE THREAD

**Issue by ldbiz** [ukwa/ukwa-ui#115]
To reproduce:

1. UKWA Home page
2. Search for anything > results page is displayed.
3. Change language (WITHOUT returning to the home page).
4. Search for anything > no results.
5. Return to home page, search for the same item as in 4 > full results.

**Comment by ldbiz** [comment]
This seems high priority to me, so I've added it to the next milestone - @nicolabingham please advise on priority if different.

**Comment by ldbiz** [comment]
@nicolabingham also there is possibly a design question about what should happen when the user clicks to change language when on the results page - at the moment the results clear and it says no results.

**Comment by nicolabingham** [comment]
This looks like a bug. I recreated it as follows: 
1) UKWA home page (English language is default) 
2) Search for "cymru" in search box
3) Search results displayed: 9,228,080  results for "cymru"
4) Staying on same page changed language option to cymraeg
5) The search results are cleared "there are no results for your query"

This bug is high priority. @jasonwebber-bl ?

WRT to the other question, there should be a clearer message to the user when they change the language and the search results are cleared. Suggest: "Your search results have been cleared."

**Comment by jasonwebber-bl** [comment]
Well spotted. @nicolabingham I agree with your suggested solution.

When in welsh, there is no link that says 'English' (it does appear to be there on Scottish Gaelic. Should i do a separate ticket for this?

**Comment by ldbiz** [comment]
@jasonwebber-bl The "English" link is there as "Saesneg" (Welsh for 'English').

**Comment by ldbiz** [comment]
The language links issue has been raised separately in #132.

**Comment by min2ha** [comment]
I've noticed that same bug was left on Footer section, where change of language links exist.

**Comment by ldbiz** [comment]
Good spot then, I missed it. Passed.
