### ISSUE TITLE
Tablet rendering: main page subtitle overlaps

### ISSUE THREAD

**Issue by ldbiz** [ukwa/ukwa-ui#23]
"Special Collections" overlaps the text.

https://dev.webarchive.org.uk/en/ukwa/collection

Samsung galaxy Tab 10 inch screen SM-T520 
Android 4.4.2
Chrome browser

**Comment by ldbiz** [comment]
![title overlay](https://user-images.githubusercontent.com/16339290/32283845-6a34391c-bf1d-11e7-8896-7c08f6149595.jpg)

**Comment by ldbiz** [comment]
ok, this is also happening on desktops.

e.g. Windows 7, Chrome

**Comment by anjackson** [comment]
Well, the bootstrap layout stuff is not done consistently at all. For each resolution, the column specifications (widths and offsets) should add up to 12. The problematic section on this page is only using 9 columns and so is needlessly squished up.

<img width="904" alt="screen shot 2017-11-28 at 11 38 13" src="https://user-images.githubusercontent.com/87843/33318120-6164dcc8-d431-11e7-855f-6a93791d734b.png">

So instead of `col-lg-2 col-lg-4 col-lg-2` we could have `col-lg-4 col-lg-4 col-lg-4` (say) and the layout would use the space up.
