### ISSUE TITLE
The new site needs a BETA banner

### ISSUE THREAD

**Issue by anjackson** [ukwa/ukwa-ui#31]
Could we implement something like the attached mock-up to make it clear that this is the beta? It’s also an opportunity to retain the survey link after they’ve dismissed the popup.

![untitled-1](https://user-images.githubusercontent.com/87843/32282160-c24dd1c6-bf18-11e7-8bed-9d96bdfd2fc5.jpg)

(also the old Access Tool needs a banner pointing users to the new site, but that must be done after this ticket.)

**Comment by ldbiz** [comment]
@min2ha connected job: #21 

The survey link in the banner should not be displayed if the user has filled out the survey (or if its not possible to detect that, then if the user has clicked on the survey link).

ie.:

1. Survey pop up not responded to: Display the link,
2. Survey dismissed without being filled out: Display the link.
3. Survey filled out: Don't display the link.

The banner will always be displayed while the application is in Beta.

**Comment by ldbiz** [comment]
Assuming the rendering change below is due to the banner changes, failed, the main elements have been shifted out of position. If this is down to a previous code change, please identify it, we need to revert.

Dev:

![image](https://user-images.githubusercontent.com/16339290/32335968-f372fb00-bfe5-11e7-9d01-cb26a4aa9332.png)


Beta:

![image](https://user-images.githubusercontent.com/16339290/32336004-08d27cc8-bfe6-11e7-8b00-7db58e30f771.png)

**Comment by ldbiz** [comment]
@min2ha that seems to be working. Jason, with you for testing. The link font and text are not quite right and aligned as the design above, but apparently that is going to be a bit of a fiddle so will be deferred via a separate issue for later.

**Comment by jasonwebber-bl** [comment]
I'm happy with this
