### ISSUE TITLE
Direct to earliest holding instead of latest

### ISSUE THREAD

**Issue by anjackson** [ukwa/ukwa-ui#35]
Currently, links to playback put a timestamp of 29991231999999 in the URL to direct to the latest copy. This seems to expose dead sites far too easily.

As our users are usually interested in the past, it makes more sense to default to showing our earliest copy rather than the latest, when we have no other timestamp information to go on.

So, can we use `{playback-prefix}10001231999999/{url}` instead? 

Do we need to add a random part to avoid locking problems? e.g. `{playback-prefix}10001231######/{url}` ?

**Comment by ldbiz** [comment]
The "end of time" default timestamp (29991231999999) was placed in as a workaround for an unsatisfactory landing result that I can't find at the moment - from (vague) memory I think that unless the instance was exactly specified (which the UI didn't have access to) it ended up on nothing. This way it at least has an instance. 

If your suggestion works, no reason we shouldn't do that though. 

However as the property (default timestamp) in question is named "future snapshot", and there is no comment to explain it, I think an additional minor code change is also appropriate rather than just changing the value to 0.

**Comment by ldbiz** [comment]
Unfortunately, this is not working with Ericom when we simply use zero in the URL. Was this why we originally did it as latest instead of earliest, or is it another issue?
