### ISSUE TITLE
Why does the code re-implement a Solr client rather than use solrj?

### ISSUE THREAD

**Issue by anjackson** [ukwa/ukwa-ui#5]
One of a set of questions that arose during an internal code review.

Although `solrj` is on the classpath and in the `pom.xml`, it does not appear to be used anywhere. The code itself however re-implements a lot of the SolrJ client logic, like building HTTP requests, setting query parameters, escaping values and so on.

Why did you re-invent this logic rather than re-using SolrJ?

(see https://cwiki.apache.org/confluence/display/solr/Using+SolrJ for more details on using SolrJ)

**Comment by bzaar** [comment]
We learned about the existence of Solrj when most of the request building logic was already implemented. We wanted to use it  (that's why there's remnants of it in pom.xml) but were too far down the line. 

I agree that using Solrj would be 'the right way'. I hope to come back to this to see how we can benefit from using Solrj.

**Comment by chrispeacockbl** [comment]
Could you just make your existing request builder delegate to SolrJ? So all the existing calls would remain the same but all the implementation would do would be to call SolrJ methods.

**Comment by bzaar** [comment]
Yes, that’s the plan. We will see if using Solrj can make our code smaller or easier to read.

**Comment by anjackson** [comment]
Thanks, although things like the IP-based access should really take priority over this at the moment.

**Comment by bzaar** [comment]
The code is a bit cleaner now that it uses SolrJ. And it was the Right Thing to Do anyway. Thanks for bringing this up, @anjackson .
